#pragma once

namespace fw {

// These are generated by version-number.cc, make sure you link with version.cc if you want to refer to them.
extern int version_major;
extern int version_minor;
extern int version_revision;
extern char const * const version_build_type;
extern char const * const version_str;
extern char const * const version_date;

}
